[package]
name = "web-base"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
postgres = "0.19"
tokio-postgres = "0.7"

toml = "0.8"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }